---
# Varnish default variables
varnish_port: 80
varnish_admin_port: 6082
varnish_backend_host: "127.0.0.1"
varnish_backend_port: 8080
varnish_memory: "256M"
varnish_storage: "malloc,{{ varnish_memory }}"
varnish_ttl: "120s"
varnish_admin_listen: "127.0.0.1" 