---
# Playbook to fix OpenSearch JVM configuration

- name: Fix OpenSearch JVM configuration
  hosts: all
  become: yes
  tasks:
    - name: Display start message
      debug:
        msg: "===== 开始修复 OpenSearch JVM 配置 ====="

    - name: Stop OpenSearch service
      systemd:
        name: opensearch
        state: stopped
      ignore_errors: yes

    - name: Check system memory
      shell: free -m | grep Mem | awk '{print $2}'
      register: system_memory
      changed_when: false

    - name: Display system memory
      debug:
        msg: "System memory: {{ system_memory.stdout }}MB"

    # 由于memory lock问题，将JVM堆大小设置得较小
    - name: Set lower heap size due to memory lock issues
      set_fact:
        heap_size_mb: 4096  # 4GB in MB
        max_heap_mb: 4096  # 4GB in MB

    - name: Set final heap size
      set_fact:
        final_heap_mb: "{{ heap_size_mb|int }}"

    - name: Display calculated heap size
      debug:
        msg: "Setting OpenSearch heap size to {{ final_heap_mb }}MB ({{ (final_heap_mb|int / 1024)|int }}GB) - reduced due to memory lock issues"

    - name: Fix OpenSearch JVM configuration
      copy:
        dest: /etc/opensearch/jvm.options
        content: |
          ## JVM configuration with reduced heap size due to memory locking issues

          ################################################################
          ## IMPORTANT: JVM heap size
          ################################################################
          -Xms{{ final_heap_mb }}m
          -Xmx{{ final_heap_mb }}m

          ################################################################
          ## Expert settings
          ################################################################
          ## GC configuration
          8-13:-XX:+UseConcMarkSweepGC
          8-13:-XX:CMSInitiatingOccupancyFraction=75
          8-13:-XX:+UseCMSInitiatingOccupancyOnly

          ## G1GC Configuration
          14-:-XX:+UseG1GC
          14-:-XX:G1ReservePercent=25
          14-:-XX:InitiatingHeapOccupancyPercent=30
          
          ## JVM temporary directory
          -Djava.io.tmpdir=${OPENSEARCH_TMPDIR}

          ## heap dumps
          -XX:+HeapDumpOnOutOfMemoryError
          -XX:HeapDumpPath=/var/lib/opensearch

          ## JVM fatal error logs
          -XX:ErrorFile=/var/log/opensearch/hs_err_pid%p.log

          ## Network settings
          -Djava.net.preferIPv4Stack=true

          ## Explicitly allow security manager (for Java 17 compatibility)
          17-:-Djava.security.manager=allow
        mode: '0640'
        owner: root
        group: opensearch

    - name: Create OpenSearch configuration file
      copy:
        dest: /etc/opensearch/opensearch.yml
        content: |
          # OpenSearch 配置文件
          cluster.name: opensearch-cluster
          node.name: node-1
          path.data: /var/lib/opensearch
          path.logs: /var/log/opensearch
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          
          # 禁用内存锁定，避免启动失败
          bootstrap.memory_lock: false
          
          # 安全设置
          plugins.security.disabled: true
          
          # 索引和分片设置
          action.auto_create_index: true
          index.number_of_shards: 5
          index.number_of_replicas: 0
          indices.query.bool.max_clause_count: 10240
        mode: '0640'
        owner: root
        group: opensearch
      ignore_errors: yes

    - name: Configure system for OpenSearch
      copy:
        dest: /etc/security/limits.d/opensearch.conf
        content: |
          # OpenSearch system limits configuration
          opensearch soft nofile 65536
          opensearch hard nofile 65536
          opensearch soft nproc 4096
          opensearch hard nproc 4096
          opensearch soft memlock unlimited
          opensearch hard memlock unlimited
        mode: '0644'
        owner: root
        group: root
      ignore_errors: yes

    - name: Set correct permissions for OpenSearch directories
      file:
        path: "{{ item }}"
        state: directory
        owner: opensearch
        group: opensearch
        mode: '0750'
        recurse: yes
      with_items:
        - /var/lib/opensearch
        - /var/log/opensearch
      ignore_errors: yes

    - name: Start OpenSearch service
      systemd:
        name: opensearch
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Display completion message
      debug:
        msg: "===== OpenSearch JVM 配置修复完成 ====="