---
# 综合修复 playbook - 修复 MySQL, OpenSearch 和 PHP 配置

- name: 综合修复 MySQL, OpenSearch 和 PHP
  hosts: all
  become: yes
  tasks:
    - name: 显示开始信息
      debug:
        msg: "===== 开始综合修复 MySQL, OpenSearch 和 PHP ====="

    # MySQL 修复部分
    - name: 停止 MySQL 服务
      systemd:
        name: mysql
        state: stopped
      ignore_errors: yes

    - name: 创建 MySQL 默认环境文件
      copy:
        dest: /etc/default/mysql
        content: "MYSQLD_OPTS=\"--user=mysql\""
        mode: '0644'
        owner: root
        group: root

    - name: 修复 MySQL 服务单元文件
      copy:
        dest: /usr/lib/systemd/system/mysql.service
        content: |
          [Unit]
          Description=Percona Server
          Documentation=man:mysqld(8)
          Documentation=http://dev.mysql.com/doc/refman/en/using-systemd.html
          After=network.target

          [Service]
          User=mysql
          Group=mysql
          Type=notify
          ExecStart=/usr/sbin/mysqld --user=mysql
          TimeoutSec=0
          PermissionsStartOnly=true
          LimitNOFILE=10000
          Environment=MYSQLD_PARENT_PID=1
          Restart=on-failure
          RestartPreventExitStatus=1

          # Set enviroment variable MYSQLD_OPTS to the empty value by default.
          # This is used to provide additional options to mysqld.
          EnvironmentFile=-/etc/default/mysql

          # Disable OOM kill on the mysqld process
          OOMScoreAdjust=-1000

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
        owner: root
        group: root

    - name: 创建 MySQL 配置文件
      copy:
        dest: /etc/mysql/my.cnf
        content: |
          [mysqld]
          user = mysql
          bind-address = 127.0.0.1
          mysqlx-bind-address = 127.0.0.1
          key_buffer_size = 256M
          max_allowed_packet = 64M
          thread_stack = 192K
          thread_cache_size = 8
          max_connections = 500
          table_open_cache = 4000
          
          # 大内存系统优化设置
          innodb_buffer_pool_size = 64G
          innodb_buffer_pool_instances = 16
          innodb_log_file_size = 1G
          innodb_log_buffer_size = 64M
          innodb_flush_log_at_trx_commit = 1
          innodb_flush_method = O_DIRECT
          
          # Character set
          character-set-server = utf8mb4
          collation-server = utf8mb4_unicode_ci
          
          # InnoDB settings
          innodb_file_per_table = 1
          innodb_open_files = 400
          innodb_io_capacity = 4000
          innodb_io_capacity_max = 8000
          
          # MyISAM settings
          myisam_recover_options = BACKUP
          
          # Logging
          log_error = /var/log/mysql/error.log
          
          # Binary logging
          server-id = 1
          log_bin = /var/log/mysql/mysql-bin.log
          expire_logs_days = 7
          
          # Slow query logging
          slow_query_log = 1
          slow_query_log_file = /var/log/mysql/mysql-slow.log
          long_query_time = 2.0
        mode: '0644'
        owner: root
        group: root
      ignore_errors: yes

    - name: 重新加载 systemd 守护进程
      systemd:
        daemon_reload: yes

    - name: 启动 MySQL 服务
      systemd:
        name: mysql
        state: started
        enabled: yes

    # PHP 修复部分
    - name: 安装 PHP 8.3 和扩展
      apt:
        name:
          - php8.3
          - php8.3-fpm
          - php8.3-cli
          - php8.3-common
          - php8.3-opcache
          - php8.3-mysql
          - php8.3-zip
          - php8.3-gd
          - php8.3-mbstring
          - php8.3-curl
          - php8.3-xml
          - php8.3-bcmath
          - php8.3-intl
          - php8.3-soap
          - php8.3-ldap
          - php8.3-imap
          - php8.3-redis
        state: present
        update_cache: yes
      ignore_errors: yes

    - name: 启动 PHP-FPM 服务
      systemd:
        name: php8.3-fpm
        state: started
        enabled: yes
      ignore_errors: yes

    # OpenSearch 完全重装部分
    - name: 停止 OpenSearch 服务
      systemd:
        name: opensearch
        state: stopped
      ignore_errors: yes
      
    - name: 卸载 OpenSearch 包
      apt:
        name: opensearch
        state: absent
        purge: yes
        autoremove: yes
      ignore_errors: yes
      
    - name: 清理 OpenSearch 数据和配置目录
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/opensearch
        - /var/lib/opensearch
        - /var/log/opensearch
        - /usr/share/opensearch
        - /etc/systemd/system/opensearch.service.d
      ignore_errors: yes
      
    - name: 重新加载 systemd
      systemd:
        daemon_reload: yes
        
    # 设置系统参数
    - name: 设置系统 kernel 参数
      copy:
        dest: /etc/sysctl.d/99-opensearch.conf
        content: |
          # OpenSearch需要的kernel参数
          vm.max_map_count = 262144
        mode: 0644
        
    - name: 应用 sysctl 设置
      command: sysctl -p /etc/sysctl.d/99-opensearch.conf
      changed_when: false
      
    # 安装依赖
    - name: 安装必要的依赖包
      apt:
        name:
          - apt-transport-https
          - gnupg
          - ca-certificates
          - openjdk-17-jdk
        state: present
        update_cache: yes
        
    # 添加 OpenSearch 仓库
    - name: 添加 OpenSearch APT key
      apt_key:
        url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
        state: present
        
    - name: 添加 OpenSearch 仓库
      apt_repository:
        repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
        state: present
        update_cache: yes
        
    # 安装 OpenSearch
    - name: 安装 OpenSearch 2.x
      apt:
        name: opensearch
        state: present
        update_cache: yes
      environment:
        DISABLE_INSTALL_DEMO_CONFIG: "true"
        DISABLE_SECURITY_PLUGIN: "true"
        
    # 创建目录
    - name: 创建必要的目录
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path: '/var/lib/opensearch', owner: 'opensearch', group: 'opensearch', mode: '0750' }
        - { path: '/var/log/opensearch', owner: 'opensearch', group: 'opensearch', mode: '0750' }
        - { path: '/etc/opensearch', owner: 'root', group: 'opensearch', mode: '0750' }
        
    # 创建极简配置
    - name: 创建极简 OpenSearch 配置
      copy:
        dest: /etc/opensearch/opensearch.yml
        content: |
          # 极简OpenSearch配置
          cluster.name: opensearch-cluster
          node.name: node-1
          path.data: /var/lib/opensearch
          path.logs: /var/log/opensearch
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          bootstrap.memory_lock: false
          plugins.security.disabled: true
        owner: root
        group: opensearch
        mode: 0640
        
    # 创建JVM配置
    - name: 创建JVM配置
      copy:
        dest: /etc/opensearch/jvm.options
        content: |
          # JVM配置 - 8GB堆内存
          -Xms8g
          -Xmx8g
          
          # GC设置
          -XX:+UseG1GC
          
          # Java 17兼容性设置
          -Djava.security.manager=allow
        owner: root
        group: opensearch
        mode: 0640
        
    # 创建systemd覆盖
    - name: 创建systemd覆盖目录
      file:
        path: /etc/systemd/system/opensearch.service.d
        state: directory
        owner: root
        group: root
        mode: 0755
        
    - name: 创建systemd覆盖配置
      copy:
        dest: /etc/systemd/system/opensearch.service.d/override.conf
        content: |
          [Service]
          LimitNOFILE=65536
          LimitNPROC=4096
          TimeoutStartSec=180
          Environment="OPENSEARCH_JAVA_OPTS=-Xms8g -Xmx8g"
          Environment="DISABLE_SECURITY_PLUGIN=true"
        owner: root
        group: root
        mode: 0644
        
    - name: 重新加载systemd配置
      systemd:
        daemon_reload: yes
        
    - name: 启动 OpenSearch 服务
      systemd:
        name: opensearch
        state: started
        enabled: yes
        
    - name: 等待 OpenSearch 启动
      wait_for:
        host: localhost
        port: 9200
        timeout: 180
      ignore_errors: yes

    - name: 显示完成信息
      debug:
        msg: "===== MySQL, OpenSearch 和 PHP 综合修复完成 =====" 