---
# Playbook to optimize Percona Server for large memory systems (64GB) with OpenSearch, Redis and RabbitMQ

- name: Optimize Percona Server for large memory system with multiple services
  hosts: all
  become: yes
  tasks:
    - name: Display start message
      debug:
        msg: "===== 开始为大内存系统(64GB)优化Percona服务器 - 平衡内存分配 ====="

    - name: Check system memory
      shell: free -m | grep Mem | awk '{print $2}'
      register: system_memory
      changed_when: false

    - name: Display system memory
      debug:
        msg: "System memory: {{ system_memory.stdout }}MB"
    
    # 计算最佳内存配置 - 考虑到其他服务
    - name: Set memory allocation facts
      set_fact:
        # OpenSearch已使用31GB
        opensearch_memory_mb: 31744
        # 预留给Redis的内存
        redis_memory_mb: 2048
        # 预留给RabbitMQ的内存
        rabbitmq_memory_mb: 1024
        # 预留给Nginx, PHP-FPM等的内存
        other_services_memory_mb: 4096
        # 预留给操作系统的内存
        os_reserved_memory_mb: 4096

    - name: Calculate available memory for MySQL
      set_fact:
        # 计算剩余可用于MySQL的内存
        available_memory_mb: "{{ system_memory.stdout|int - opensearch_memory_mb|int - redis_memory_mb|int - rabbitmq_memory_mb|int - other_services_memory_mb|int - os_reserved_memory_mb|int }}"

    # 计算最佳内存配置
    - name: Calculate optimal buffer pool size
      set_fact:
        # 使用可用内存的75%作为InnoDB缓冲池大小
        buffer_pool_size: "{{ ((available_memory_mb|int) * 0.75)|int }}M"
        # 缓冲池实例数 - 通常设置为CPU内核数或适当的数字
        buffer_pool_instances: "{{ [ansible_processor_vcpus, 8]|min }}"
        # 日志文件大小 - 通常为缓冲池大小的4-8%
        log_file_size: "{{ ((available_memory_mb|int) * 0.04)|int }}M"
        # 最大连接数 - 根据服务器负载调整
        max_connections: "{{ [((system_memory.stdout|int) / 200)|int, 500]|min }}"

    - name: Display calculated settings
      debug:
        msg: |
          系统总内存: {{ system_memory.stdout }}MB
          OpenSearch已分配: {{ opensearch_memory_mb }}MB
          Redis预留: {{ redis_memory_mb }}MB
          RabbitMQ预留: {{ rabbitmq_memory_mb }}MB
          其他服务预留: {{ other_services_memory_mb }}MB
          操作系统预留: {{ os_reserved_memory_mb }}MB
          MySQL可用内存: {{ available_memory_mb }}MB
          
          MySQL优化设置:
          InnoDB Buffer Pool Size: {{ buffer_pool_size }}
          Buffer Pool Instances: {{ buffer_pool_instances }}
          Log File Size: {{ log_file_size }}
          Max Connections: {{ max_connections }}

    - name: Stop MySQL service
      systemd:
        name: mysql
        state: stopped

    - name: Backup existing MySQL configuration
      copy:
        src: /etc/mysql/my.cnf
        dest: /etc/mysql/my.cnf.backup
        remote_src: yes
      ignore_errors: yes

    - name: Configure Percona Server for balanced memory system
      copy:
        dest: /etc/mysql/my.cnf
        content: |
          [mysqld]
          # 基本设置
          user = mysql
          pid-file = /var/run/mysqld/mysqld.pid
          socket = /var/run/mysqld/mysqld.sock
          port = 3306
          basedir = /usr
          datadir = /var/lib/mysql
          tmpdir = /tmp
          lc-messages-dir = /usr/share/mysql

          # 安全设置
          local-infile = 0
          symbolic-links = 0

          # 字符集设置
          character-set-server = utf8mb4
          collation-server = utf8mb4_unicode_ci

          # InnoDB缓冲池 - 均衡内存优化
          innodb_buffer_pool_size = {{ buffer_pool_size }}
          innodb_buffer_pool_instances = {{ buffer_pool_instances }}
          innodb_log_file_size = {{ log_file_size }}
          innodb_flush_log_at_trx_commit = 1
          innodb_flush_method = O_DIRECT
          innodb_file_per_table = 1
          
          # 缓冲和缓存设置 - 适度配置
          innodb_log_buffer_size = 32M
          
          # 禁用查询缓存 (MySQL 8.0已移除)
          query_cache_type = 0
          query_cache_size = 0
          
          # 表缓存设置 - 适度配置
          table_open_cache = 2000
          table_definition_cache = 1000
          
          # 临时表设置 - 适度配置
          tmp_table_size = 32M
          max_heap_table_size = 32M
          
          # 并发连接设置
          max_connections = {{ max_connections }}
          max_allowed_packet = 32M
          thread_stack = 256K
          thread_cache_size = 16
          
          # MyISAM - 虽然主要使用InnoDB，但保留一些MyISAM设置
          key_buffer_size = 16M
          myisam-recover-options = BACKUP
          
          # 排序缓冲区 - 适度配置
          sort_buffer_size = 4M
          join_buffer_size = 4M
          read_buffer_size = 2M
          read_rnd_buffer_size = 4M
          
          # 性能优化
          innodb_io_capacity = 2000
          innodb_io_capacity_max = 4000
          
          # 日志设置
          log_error = /var/log/mysql/error.log
          slow_query_log = 1
          slow_query_log_file = /var/log/mysql/mysql-slow.log
          long_query_time = 2
          
          # 二进制日志
          server-id = 1
          log_bin = /var/log/mysql/mysql-bin.log
          binlog_format = ROW
          expire_logs_days = 7
          max_binlog_size = 100M
          
          [client]
          port = 3306
          socket = /var/run/mysqld/mysqld.sock
          default-character-set = utf8mb4
          
          [mysqldump]
          quick
          quote-names
          max_allowed_packet = 32M
        mode: '0644'
        owner: root
        group: root

    - name: Start MySQL service
      systemd:
        name: mysql
        state: started
        enabled: yes

    - name: Verify MySQL is running
      command: systemctl status mysql
      register: mysql_status
      changed_when: false
      ignore_errors: yes

    - name: Display MySQL status
      debug:
        msg: "MySQL服务状态: {{ 'Running' if 'active (running)' in mysql_status.stdout else 'Failed to start' }}"

    - name: Display MySQL buffer pool information
      shell: mysql -e "SHOW VARIABLES LIKE 'innodb_buffer%';" || echo "无法获取MySQL变量信息"
      register: mysql_vars
      changed_when: false
      ignore_errors: yes

    - name: Display MySQL configuration
      debug:
        msg: "{{ mysql_vars.stdout_lines if mysql_vars.stdout_lines is defined else 'MySQL information not available' }}"

    - name: Display completion message
      debug:
        msg: "===== Percona服务器内存优化完成 =====" 