---
# 综合修复 playbook - 修复 MySQL 和 OpenSearch 配置

- name: 综合修复 MySQL 和 OpenSearch
  hosts: all
  become: yes
  tasks:
    - name: 显示开始信息
      debug:
        msg: "===== 开始综合修复 MySQL 和 OpenSearch ====="

    # MySQL 修复部分
    - name: 停止 MySQL 服务
      systemd:
        name: mysql
        state: stopped
      ignore_errors: yes

    - name: 创建 MySQL 默认环境文件
      copy:
        dest: /etc/default/mysql
        content: "MYSQLD_OPTS=\"--user=mysql\""
        mode: '0644'
        owner: root
        group: root

    - name: 修复 MySQL 服务单元文件
      copy:
        dest: /usr/lib/systemd/system/mysql.service
        content: |
          [Unit]
          Description=Percona Server
          Documentation=man:mysqld(8)
          Documentation=http://dev.mysql.com/doc/refman/en/using-systemd.html
          After=network.target

          [Service]
          User=mysql
          Group=mysql
          Type=notify
          ExecStart=/usr/sbin/mysqld --user=mysql
          TimeoutSec=0
          PermissionsStartOnly=true
          LimitNOFILE=10000
          Environment=MYSQLD_PARENT_PID=1
          Restart=on-failure
          RestartPreventExitStatus=1

          # Set enviroment variable MYSQLD_OPTS to the empty value by default.
          # This is used to provide additional options to mysqld.
          EnvironmentFile=-/etc/default/mysql

          # Disable OOM kill on the mysqld process
          OOMScoreAdjust=-1000

          [Install]
          WantedBy=multi-user.target
        mode: '0644'
        owner: root
        group: root

    - name: 创建 MySQL 配置文件
      copy:
        dest: /etc/mysql/my.cnf
        content: |
          [mysqld]
          user = mysql
          bind-address = 127.0.0.1
          mysqlx-bind-address = 127.0.0.1
          key_buffer_size = 256M
          max_allowed_packet = 64M
          thread_stack = 192K
          thread_cache_size = 8
          max_connections = 500
          table_open_cache = 4000
          
          # 大内存系统优化设置
          innodb_buffer_pool_size = 64G
          innodb_buffer_pool_instances = 16
          innodb_log_file_size = 1G
          innodb_log_buffer_size = 64M
          innodb_flush_log_at_trx_commit = 1
          innodb_flush_method = O_DIRECT
          
          # Character set
          character-set-server = utf8mb4
          collation-server = utf8mb4_unicode_ci
          
          # InnoDB settings
          innodb_file_per_table = 1
          innodb_open_files = 400
          innodb_io_capacity = 4000
          innodb_io_capacity_max = 8000
          
          # MyISAM settings
          myisam_recover_options = BACKUP
          
          # Logging
          log_error = /var/log/mysql/error.log
          
          # Binary logging
          server-id = 1
          log_bin = /var/log/mysql/mysql-bin.log
          expire_logs_days = 7
          
          # Slow query logging
          slow_query_log = 1
          slow_query_log_file = /var/log/mysql/mysql-slow.log
          long_query_time = 2.0
        mode: '0644'
        owner: root
        group: root
      ignore_errors: yes

    - name: 重新加载 systemd 守护进程
      systemd:
        daemon_reload: yes

    - name: 启动 MySQL 服务
      systemd:
        name: mysql
        state: started
        enabled: yes

    # OpenSearch 修复部分
    - name: 停止 OpenSearch 服务
      systemd:
        name: opensearch
        state: stopped
      ignore_errors: yes

    # 设置固定的 JVM 堆大小为 31GB，考虑到大内存系统的最佳做法
    # 对于搜索引擎，不要超过31GB的堆大小，即使有128GB内存
    - name: 设置优化的 OpenSearch 堆大小
      set_fact:
        final_heap_mb: 31744  # 31GB

    - name: 显示配置的堆大小
      debug:
        msg: "设置 OpenSearch 堆大小为 {{ final_heap_mb }}MB ({{ (final_heap_mb|int / 1024)|int }}GB) - 针对大内存系统(128GB)优化"

    - name: 删除现有的 OpenSearch 配置文件
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/opensearch/opensearch.yml
        - /etc/opensearch/jvm.options
      ignore_errors: yes

    - name: 修复 OpenSearch JVM 配置
      copy:
        dest: /etc/opensearch/jvm.options
        content: |
          ## JVM configuration for large memory system (128GB)

          ################################################################
          ## IMPORTANT: JVM heap size
          ################################################################
          -Xms{{ final_heap_mb }}m
          -Xmx{{ final_heap_mb }}m

          ################################################################
          ## Expert settings optimized for large memory system
          ################################################################
          ## GC configuration
          8-13:-XX:+UseConcMarkSweepGC
          8-13:-XX:CMSInitiatingOccupancyFraction=75
          8-13:-XX:+UseCMSInitiatingOccupancyOnly

          ## G1GC Configuration
          14-:-XX:+UseG1GC
          14-:-XX:G1ReservePercent=25
          14-:-XX:InitiatingHeapOccupancyPercent=30
          
          ## Large page settings for better performance
          -XX:+UseLargePages
          -XX:LargePageSizeInBytes=2m

          ## JVM temporary directory
          -Djava.io.tmpdir=${OPENSEARCH_TMPDIR}

          ## heap dumps
          -XX:+HeapDumpOnOutOfMemoryError
          -XX:HeapDumpPath=/var/lib/opensearch

          ## JVM fatal error logs
          -XX:ErrorFile=/var/log/opensearch/hs_err_pid%p.log

          ## Network settings
          -Djava.net.preferIPv4Stack=true

          ## Explicitly allow security manager (for Java 17 compatibility)
          17-:-Djava.security.manager=allow
        mode: '0640'
        owner: root
        group: opensearch

    - name: 创建 OpenSearch 配置文件
      copy:
        dest: /etc/opensearch/opensearch.yml
        content: |
          # OpenSearch 配置文件 - 针对128GB大内存系统优化
          cluster.name: opensearch-cluster
          node.name: node-1
          path.data: /var/lib/opensearch
          path.logs: /var/log/opensearch
          network.host: 0.0.0.0
          http.port: 9200
          discovery.type: single-node
          
          # 内存设置
          bootstrap.memory_lock: true
          
          # 安全设置
          plugins.security.disabled: true
          
          # 索引和分片设置
          action.auto_create_index: true
          index.number_of_shards: 5
          index.number_of_replicas: 0
          indices.query.bool.max_clause_count: 10240
        mode: '0640'
        owner: root
        group: opensearch

    - name: 配置系统限制
      copy:
        dest: /etc/security/limits.d/opensearch.conf
        content: |
          # OpenSearch system limits configuration
          opensearch soft nofile 65536
          opensearch hard nofile 65536
          opensearch soft nproc 4096
          opensearch hard nproc 4096
          opensearch soft memlock unlimited
          opensearch hard memlock unlimited
        mode: '0644'
        owner: root
        group: root
      ignore_errors: yes

    - name: 设置 OpenSearch 目录的正确权限
      file:
        path: "{{ item }}"
        state: directory
        owner: opensearch
        group: opensearch
        mode: '0750'
        recurse: yes
      with_items:
        - /var/lib/opensearch
        - /var/log/opensearch
      ignore_errors: yes

    - name: 启动 OpenSearch 服务
      systemd:
        name: opensearch
        state: started
        enabled: yes

    - name: 显示完成信息
      debug:
        msg: "===== MySQL 和 OpenSearch 综合修复完成 =====" 