---
# LEMP Stack Playbook for Ubuntu 24.04 with additional components
- name: Install LEMP Stack and Additional Components
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

  roles:
    - common
    - nginx
    - php
    - composer
    - percona
    - redis
    - rabbitmq
    - varnish
    - opensearch
    - fail2ban
    - certbot
    - phpmyadmin
    - webmin 