---
# Playbook to install OpenSearch 2.12.0 with minimal configuration
- name: Install OpenSearch
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    # 获取系统内存信息，用于合理设置JVM堆大小
    - name: Get system memory
      shell: grep MemTotal /proc/meminfo | awk '{print $2}'
      register: system_memory
      changed_when: false

    - name: Calculate OpenSearch heap size
      set_fact:
        # 设置固定28GB内存
        heap_size_mb: "28672"

    - name: Display calculated heap size
      debug:
        msg: "Setting OpenSearch heap size to {{ heap_size_mb }}MB ({{ (heap_size_mb|int / 1024)|int }}GB)"

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - gnupg
          - ca-certificates
          - openjdk-17-jdk
        state: present
        update_cache: yes

    - name: Add OpenSearch apt key
      apt_key:
        url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
        state: present

    - name: Add OpenSearch repository
      apt_repository:
        repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
        state: present
        update_cache: yes

    # 完全清理现有的 OpenSearch
    - name: Stop OpenSearch service if running
      systemd:
        name: opensearch
        state: stopped
      ignore_errors: yes

    - name: Completely remove existing OpenSearch
      apt:
        name: opensearch
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Remove existing OpenSearch data and config directories
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/opensearch
        - /var/lib/opensearch
        - /var/log/opensearch
        - /usr/share/opensearch
        - /var/run/opensearch
      ignore_errors: yes

    - name: Create necessary directories
      file:
        path: "{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      with_items:
        - /var/run/opensearch
        - /var/lib/opensearch
        - /var/log/opensearch

    # 预先创建demo配置日志文件以避免安装过程中的错误
    - name: Create demo configuration log file
      file:
        path: /var/log/opensearch/install_demo_configuration.log
        state: touch
        owner: root
        group: root
        mode: '0644'
      ignore_errors: yes

    # 先准备好配置文件，避免安装过程中使用默认配置
    - name: Create OpenSearch directory
      file:
        path: /etc/opensearch
        state: directory
        owner: root
        group: root
        mode: '0755'

    # 配置系统限制
    - name: Configure system limits for OpenSearch
      copy:
        dest: /etc/security/limits.d/opensearch.conf
        content: |
          # OpenSearch系统限制配置
          opensearch soft nofile 65536
          opensearch hard nofile 65536
          opensearch soft nproc 4096
          opensearch hard nproc 4096
          opensearch soft memlock unlimited
          opensearch hard memlock unlimited
        mode: '0644'
        owner: root
        group: root

    # 安装 OpenSearch
    - name: Install OpenSearch
      apt:
        name: opensearch=2.12.0
        state: present
        update_cache: yes
      environment:
        OPENSEARCH_JAVA_OPTS: "-Xms28g -Xmx28g"
        OPENSEARCH_INITIAL_ADMIN_PASSWORD: "Str0ngP@ssw0rd!2025X#"
        DISABLE_INSTALL_DEMO_CONFIG: "true"
        DISABLE_SECURITY_PLUGIN: "true"
      ignore_errors: yes

    # 使用dpkg强制完成安装，忽略可能的错误
    - name: Force configure OpenSearch package
      shell: sudo dpkg --configure -a
      ignore_errors: yes

    # 基本配置 - 注意：避免使用索引级别设置
    - name: Configure OpenSearch - proper configuration
      copy:
        dest: /etc/opensearch/opensearch.yml
        content: |
          # OpenSearch配置文件 - 经过优化的安全配置
          cluster.name: opensearch-cluster
          node.name: node-1
          
          # 路径设置
          path.data: /var/lib/opensearch
          path.logs: /var/log/opensearch
          
          # 网络设置 - 允许从任何IP访问
          network.host: 0.0.0.0
          http.port: 9200
          transport.host: 0.0.0.0
          transport.port: 9300
          
          # 单节点发现
          discovery.type: single-node
          
          # 内存设置 - 禁用内存锁定
          bootstrap.memory_lock: false
          
          # 禁用安全插件
          plugins.security.disabled: true
          
          # 性能优化设置
          thread_pool.write.queue_size: 1000
          thread_pool.search.queue_size: 1000
          
          # 索引操作设置 - 注意：只使用集群级别设置
          action.auto_create_index: true
          
          # 禁用性能分析器
          opensearch.performanceanalyzer.enabled: false
          plugins.performance_analyzer.enabled: false
        mode: '0640'
        owner: root
        group: opensearch
      ignore_errors: yes

    - name: Configure JVM options - optimized
      copy:
        dest: /etc/opensearch/jvm.options
        content: |
          ## JVM配置文件 - 使用28GB内存
          
          # 堆大小设置 - 28GB内存
          -Xms28g
          -Xmx28g
          
          # GC设置
          -XX:+UseG1GC
          
          # 临时目录
          -Djava.io.tmpdir=${OPENSEARCH_TMPDIR}
          
          # Java 17兼容性
          17-:-Djava.security.manager=allow
        mode: '0640'
        owner: root
        group: opensearch
      ignore_errors: yes

    # 禁用性能分析器插件
    - name: Create performance-analyzer config directory
      file:
        path: /usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/
        state: directory
        owner: opensearch
        group: opensearch
        mode: '0750'
      ignore_errors: yes

    - name: Disable performance-analyzer plugin
      copy:
        dest: /usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/performance-analyzer.properties
        content: |
          # 禁用performance-analyzer
          performance-analyzer.enabled: false
          rca.enabled: false
        mode: '0640'
        owner: opensearch
        group: opensearch
      ignore_errors: yes

    # 设置权限
    - name: Set correct permissions for OpenSearch directories
      file:
        path: "{{ item }}"
        state: directory
        owner: opensearch
        group: opensearch
        mode: '0750'
        recurse: yes
      with_items:
        - /var/lib/opensearch
        - /var/log/opensearch
        - /var/run/opensearch
      ignore_errors: yes

    # 确保服务单元文件正确
    - name: Update OpenSearch service unit
      copy:
        dest: /usr/lib/systemd/system/opensearch.service
        content: |
          [Unit]
          Description=OpenSearch
          Documentation=https://opensearch.org/
          Wants=network-online.target
          After=network-online.target
          
          [Service]
          Type=simple
          RuntimeDirectory=opensearch
          PrivateTmp=true
          Environment=OPENSEARCH_HOME=/usr/share/opensearch
          Environment=OPENSEARCH_PATH_CONF=/etc/opensearch
          Environment=PID_DIR=/var/run/opensearch
          Environment=OPENSEARCH_SD_NOTIFY=true
          EnvironmentFile=-/etc/default/opensearch
          
          WorkingDirectory=/usr/share/opensearch
          
          User=opensearch
          Group=opensearch
          
          ExecStart=/usr/share/opensearch/bin/systemd-entrypoint -p ${PID_DIR}/opensearch.pid --quiet
          
          # 标准输出和标准错误重定向到日志
          StandardOutput=journal
          StandardError=inherit
          
          # 确保文件资源不会被耗尽
          LimitNOFILE=65536
          LimitNPROC=4096
          # 允许内存锁定
          LimitMEMLOCK=infinity
          
          # 最大超时时间
          TimeoutStopSec=75
          
          # 在服务失败时重启
          Restart=always
          RestartSec=15
          
          [Install]
          WantedBy=multi-user.target
        mode: '0644'
        owner: root
        group: root
      ignore_errors: yes
    
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
        
    # 创建opensearch-keystore
    - name: Create OpenSearch keystore
      shell: sudo -u opensearch /usr/share/opensearch/bin/opensearch-keystore create
      args:
        creates: /etc/opensearch/opensearch.keystore
      ignore_errors: yes

    # 启动服务
    - name: Start and enable OpenSearch service
      systemd:
        name: opensearch
        state: started
        enabled: yes
      ignore_errors: yes

    # 检查服务状态 - 给予更多启动时间
    - name: Wait for OpenSearch to start
      wait_for:
        host: 127.0.0.1
        port: 9200
        delay: 20
        timeout: 120
      ignore_errors: yes
      register: startup_result

    - name: Check if OpenSearch is running
      shell: systemctl status opensearch | grep -o "active" || echo "not running"
      register: os_status
      changed_when: false
      ignore_errors: yes

    - name: Display status
      debug:
        msg: "OpenSearch服务状态: {{ 'Active' if os_status.stdout == 'active' else 'Failed' }}"
        
    - name: Test OpenSearch API
      uri:
        url: http://localhost:9200
        method: GET
        status_code: 200
      register: api_response
      ignore_errors: yes
        
    - name: Display API status
      debug:
        msg: "OpenSearch API响应: {{ 'Success' if api_response.status == 200 else 'Failed' }}"
        verbosity: 0
      when: api_response is defined

    - name: Clean data directory and try again if startup failed
      block:
        - name: Stop OpenSearch
          systemd:
            name: opensearch
            state: stopped
          ignore_errors: yes
          
        - name: Clean OpenSearch data
          file:
            path: /var/lib/opensearch
            state: absent
          ignore_errors: yes
          
        - name: Recreate data directory
          file:
            path: /var/lib/opensearch
            state: directory
            owner: opensearch
            group: opensearch
            mode: '0750'
          ignore_errors: yes
          
        - name: Try to start OpenSearch again
          systemd:
            name: opensearch
            state: started
          ignore_errors: yes
          
        - name: Wait for second startup attempt
          wait_for:
            host: 127.0.0.1
            port: 9200
            delay: 10
            timeout: 120
          ignore_errors: yes
      when: startup_result is failed

    # 创建systemd覆盖目录
    - name: Create systemd override directory
      file:
        path: /etc/systemd/system/opensearch.service.d
        state: directory
        owner: root
        group: root
        mode: '0755'

    # 添加systemd覆盖配置
    - name: Create systemd override for OpenSearch
      copy:
        dest: /etc/systemd/system/opensearch.service.d/override.conf
        content: |
          [Service]
          LimitMEMLOCK=infinity
          LimitNOFILE=65536
          LimitNPROC=4096
          TimeoutStartSec=600
          Environment="OPENSEARCH_JAVA_OPTS=-Xms28g -Xmx28g"
          Environment="DISABLE_SECURITY_PLUGIN=true"
          Environment="OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin"
          Environment="DISABLE_INSTALL_DEMO_CONFIG=true"
          Restart=always
          RestartSec=30s
        mode: '0644'
        owner: root
        group: root

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes 