---
# Playbook to uninstall PHP

- name: Uninstall PHP
  hosts: all
  become: yes
  tasks:
    - name: Display start message
      debug:
        msg: "===== 开始卸载 PHP ====="

    - name: Stop PHP-FPM services
      systemd:
        name: "{{ item }}"
        state: stopped
      with_items:
        - php8.3-fpm
        - php8.4-fpm
      ignore_errors: yes

    - name: Remove PHP symlinks
      file:
        path: "/usr/bin/php"
        state: absent
      ignore_errors: yes

    - name: Remove PHP 8.3 packages
      apt:
        name: "php8.3*"
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Remove PHP 8.4 packages
      apt:
        name: "php8.4*"
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Remove other PHP packages
      apt:
        name:
          - php
          - php-common
          - php-cli
        state: absent
        purge: yes
      ignore_errors: yes

    - name: Remove PHP repository
      apt_repository:
        repo: ppa:ondrej/php
        state: absent
        update_cache: yes
      ignore_errors: yes

    - name: Remove PHP configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/php
        - /etc/apt/preferences.d/php
      ignore_errors: yes

    - name: Clean apt cache
      apt:
        autoclean: yes
        autoremove: yes
      ignore_errors: yes

    - name: Display completion message
      debug:
        msg: "===== PHP 卸载完成 =====" 