---
# Composer installation and configuration tasks

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-setup.php
    mode: '0755'

- name: Install Composer
  shell: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer --version=2.7.9
  args:
    creates: /usr/local/bin/composer

- name: Make Composer executable
  file:
    path: /usr/local/bin/composer
    mode: '0755'
    state: file

- name: Clean up Composer installer
  file:
    path: /tmp/composer-setup.php
    state: absent 