---
# OpenSearch installation and configuration tasks

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - gnupg
      - ca-certificates
      - openjdk-17-jdk
    state: present
    update_cache: yes

- name: Add OpenSearch apt key
  apt_key:
    url: https://artifacts.opensearch.org/publickeys/opensearch.pgp
    state: present

- name: Add OpenSearch repository
  apt_repository:
    repo: "deb https://artifacts.opensearch.org/releases/bundle/opensearch/2.x/apt stable main"
    state: present
    update_cache: yes

# 完全清理现有的 OpenSearch 配置
- name: Stop OpenSearch service if running
  systemd:
    name: opensearch
    state: stopped
  ignore_errors: yes

- name: Completely remove existing OpenSearch
  apt:
    name: opensearch
    state: absent
    purge: yes
  ignore_errors: yes

- name: Remove existing OpenSearch data and config directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/opensearch
    - /var/lib/opensearch
    - /var/log/opensearch
    - /usr/share/opensearch
  ignore_errors: yes

- name: Create necessary directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /var/run/opensearch
    - /var/lib/opensearch
    - /var/log/opensearch

# 预先创建demo配置日志文件以避免安装过程中的错误
- name: Create demo configuration log file
  file:
    path: /var/log/opensearch/install_demo_configuration.log
    state: touch
    owner: root
    group: root
    mode: '0644'
  ignore_errors: yes

# 安装 OpenSearch
- name: Install OpenSearch
  apt:
    name: opensearch=2.12.0
    state: present
    update_cache: yes
  environment:
    OPENSEARCH_INITIAL_ADMIN_PASSWORD: "StrongAdminPassword123!"
    DISABLE_INSTALL_DEMO_CONFIG: "true"
    DISABLE_SECURITY_PLUGIN: "true"
  ignore_errors: yes

# 确保配置目录存在
- name: Ensure OpenSearch configuration directory exists
  file:
    path: /etc/opensearch
    state: directory
    owner: root
    group: opensearch
    mode: '0750'
  ignore_errors: yes

# 配置 OpenSearch
- name: Configure OpenSearch
  template:
    src: opensearch.yml.j2
    dest: /etc/opensearch/opensearch.yml
    owner: root
    group: opensearch
    mode: '0640'
  ignore_errors: yes

- name: Configure JVM options
  template:
    src: jvm.options.j2
    dest: /etc/opensearch/jvm.options
    owner: root
    group: opensearch
    mode: '0640'
  ignore_errors: yes

# 禁用性能分析器插件
- name: Create performance-analyzer-rca config directory
  file:
    path: /usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/
    state: directory
    owner: opensearch
    group: opensearch
    mode: '0750'
  ignore_errors: yes

- name: Disable performance-analyzer plugin
  copy:
    dest: /usr/share/opensearch/plugins/opensearch-performance-analyzer/pa_config/performance-analyzer.properties
    content: |
      # 禁用performance-analyzer
      performance-analyzer.enabled: false
      rca.enabled: false
    mode: '0640'
    owner: opensearch
    group: opensearch
  ignore_errors: yes

# 确保数据和日志目录权限正确
- name: Set correct permissions for OpenSearch directories
  file:
    path: "{{ item }}"
    state: directory
    owner: opensearch
    group: opensearch
    mode: '0750'
    recurse: yes
  with_items:
    - /var/lib/opensearch
    - /var/log/opensearch
  ignore_errors: yes

- name: Start and enable OpenSearch service
  systemd:
    name: opensearch
    state: started
    enabled: yes
  ignore_errors: yes

- name: Wait for OpenSearch to start
  wait_for:
    host: 127.0.0.1
    port: 9200
    delay: 10
    timeout: 180
  ignore_errors: yes 