---
# Percona Server uninstallation tasks

- name: Stop MySQL service if running
  systemd:
    name: mysql
    state: stopped
  ignore_errors: yes

- name: Remove my.cnf alternatives if they exist
  command: update-alternatives --remove my.cnf /etc/mysql/my.cnf
  ignore_errors: yes

- name: Check if /etc/mysql directory exists
  stat:
    path: /etc/mysql
  register: mysql_dir

- name: Backup MySQL configuration if it exists
  copy:
    src: /etc/mysql/my.cnf
    dest: /etc/mysql/my.cnf.backup
    remote_src: yes
  when: mysql_dir.stat.exists
  ignore_errors: yes

- name: Remove Percona Server packages
  apt:
    name:
      - percona-server-server
      - percona-server-client
      - percona-server-common
    state: absent
    purge: yes
  ignore_errors: yes

- name: Clean up MySQL directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/mysql
    - /var/lib/mysql
  ignore_errors: yes

- name: Remove Percona repository
  apt_repository:
    repo: "deb http://repo.percona.com/apt {{ ansible_distribution_release }} main"
    state: absent
    update_cache: yes
  ignore_errors: yes

- name: Remove Percona repository package
  apt:
    name: percona-release
    state: absent
    purge: yes
  ignore_errors: yes

- name: Clean apt cache
  apt:
    autoclean: yes
  ignore_errors: yes

- name: Autoremove unused packages
  apt:
    autoremove: yes
  ignore_errors: yes

- name: Force dpkg to configure any pending packages
  command: dpkg --configure -a
  ignore_errors: yes 