---
# OpenSearch default variables
opensearch_cluster_name: "opensearch-cluster"
opensearch_node_name: "node-1"
opensearch_http_port: 9200
opensearch_transport_port: 9300
opensearch_network_host: "0.0.0.0"
opensearch_discovery_type: "single-node"
opensearch_heap_size: "8g"
opensearch_data_path: "/var/lib/opensearch"
opensearch_logs_path: "/var/log/opensearch"

# 内存锁定设置
opensearch_bootstrap_memory_lock: false

# Admin password
opensearch_admin_password: "StrongAdminPassword123!"

# Security settings
opensearch_security_enabled: false

# 性能优化参数
opensearch_thread_pool_write_queue_size: 1000
opensearch_thread_pool_search_queue_size: 1000
opensearch_action_auto_create_index: true
opensearch_indices_queries_cache_size: "20%"
opensearch_indices_memory_index_buffer_size: "30%"
opensearch_indices_fielddata_cache_size: "40%"
opensearch_search_max_buckets: 10000 