---
# OpenSearch default variables
opensearch_cluster_name: "opensearch-cluster"
opensearch_node_name: "node-1"
opensearch_http_port: 9200
opensearch_transport_port: 9300
opensearch_network_host: "127.0.0.1"
opensearch_discovery_type: "single-node"
opensearch_heap_size: "1g"
opensearch_data_path: "/var/lib/opensearch"
opensearch_logs_path: "/var/log/opensearch"

# Admin password
opensearch_admin_password: "StrongAdminPassword123!"

# Security settings
opensearch_security_enabled: false 