---
# PHP installation and configuration tasks

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - lsb-release
      - software-properties-common
    state: present
    update_cache: yes

- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes
  ignore_errors: yes

- name: Add PHP repository (alternative)
  shell: |
    add-apt-repository -y ppa:ondrej/php
    apt-get update
  args:
    creates: /etc/apt/sources.list.d/ondrej-ubuntu-php-*.list
  when: ansible_distribution_release == "noble"

# 设置 APT 偏好，确保只安装 PHP 8.3
- name: Configure APT preferences for PHP 8.3
  copy:
    dest: /etc/apt/preferences.d/php
    content: |
      Package: php*
      Pin: release *
      Pin-Priority: 100

      Package: php8.3*
      Pin: release *
      Pin-Priority: 900

      Package: php8.4*
      Pin: release *
      Pin-Priority: -1
    mode: '0644'

# 卸载 PHP 8.4（如果已安装）
- name: Check if PHP 8.4 is installed
  shell: dpkg -l | grep -q "php8.4"
  register: php84_check
  failed_when: false
  changed_when: false

- name: Remove PHP 8.4 if installed
  apt:
    name: "php8.4*"
    state: absent
    purge: yes
  when: php84_check.rc == 0
  ignore_errors: yes

- name: Install PHP and extensions
  apt:
    name:
      - php8.3=8.3.19-1+ubuntu24.04.1+deb.sury.org+1
      - php8.3-fpm=8.3.19-1+ubuntu24.04.1+deb.sury.org+1
      - php8.3-cli=8.3.19-1+ubuntu24.04.1+deb.sury.org+1
      - php8.3-common=8.3.19-1+ubuntu24.04.1+deb.sury.org+1
      - php8.3-opcache
      - php8.3-mysql
      - php8.3-zip
      - php8.3-gd
      - php8.3-mbstring
      - php8.3-curl
      - php8.3-xml
      - php8.3-bcmath
      - php8.3-intl
      - php8.3-soap
      - php8.3-ldap
      - php8.3-imap
      - php8.3-redis
      - php8.3-imagick
    state: present
    update_cache: yes
    force: yes
  ignore_errors: yes

- name: Configure PHP-FPM
  template:
    src: www.conf.j2
    dest: /etc/php/8.3/fpm/pool.d/www.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Configure PHP
  template:
    src: php.ini.j2
    dest: /etc/php/8.3/fpm/php.ini
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Configure PHP CLI
  template:
    src: php-cli.ini.j2
    dest: /etc/php/8.3/cli/php.ini
    owner: root
    group: root
    mode: '0644'

- name: Configure PHP opcache
  template:
    src: opcache.ini.j2
    dest: /etc/php/8.3/mods-available/opcache.ini
    owner: root
    group: root
    mode: '0644'
  notify: restart php-fpm

- name: Start and enable PHP-FPM service
  systemd:
    name: php8.3-fpm
    state: started
    enabled: yes

# 创建 PHP 命令的符号链接
- name: Create PHP symlinks
  file:
    src: "/usr/bin/php8.3"
    dest: "/usr/bin/php"
    state: link
  ignore_errors: yes 