---
# Webmin installation and configuration tasks

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - gnupg2
      - perl
      - libnet-ssleay-perl
      - openssl
      - libauthen-pam-perl
      - libpam-runtime
      - libio-pty-perl
      - apt-show-versions
      - python3
    state: present
    update_cache: yes

- name: Add Webmin apt key
  apt_key:
    url: http://www.webmin.com/jcameron-key.asc
    state: present

- name: Add Webmin repository
  apt_repository:
    repo: deb http://download.webmin.com/download/repository sarge contrib
    state: present
    update_cache: yes

- name: Install Webmin
  apt:
    name: webmin
    state: latest
    update_cache: yes

- name: Configure Webmin
  template:
    src: miniserv.conf.j2
    dest: /etc/webmin/miniserv.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart webmin

- name: Allow Webmin through UFW
  ufw:
    rule: allow
    port: "{{ webmin_port }}"
    proto: tcp 